---
title: "Precipitation"
author: 'Liang Cai'
date: "2022/11/24"
output: html_document
---
# Define the working directory for the entire markdown file to enable relative path
```{r setup, include=FALSE}
rm(list=ls())

#Define relative path
knitr::opts_knit$set(root.dir = '/Users/ashitakarl/Dropbox/WB/MENA_WorldBank/')
knitr::opts_chunk$set(echo = TRUE)
```

#Load packages
```{r}
library(raster)
library(terra)
library(tidyverse)
library(ggplot2)
library(sf)
library(ncdf4)
```

#Define data directories

```{r}
#Confirm path
dir_shp <- './Boundaries/'                                                                                                            #Confirm path
dir_precip <- '/Users/ashitakarl/Desktop/Project/WB/Raw data/Precipitation 2001-2020/'                    #Confirm path
dir_out <- '/Users/ashitakarl/Library/CloudStorage/Dropbox/WB/MENA_WorldBank/Data/Precipitation/'
dir_index <- './Index/'    
CRS_WGS <- '+proj=longlat +datum=WGS84 +no_defs'
```

#Include functions for clipping and extract values
```{r}
#Function to extract values
desc_stats_fun <- function(clipped, shp){   
  
    # Estimate basic stats per rayon
    stats = terra::extract(x = clipped, y = shp, df=TRUE)
    
    colnames(stats)[1:2] <- c('ID', 'value')
  
    desc_stats <- stats %>%
      group_by(ID) %>% 
      summarise(mean=mean(value, na.rm=TRUE), 
                max=max(value, na.rm=TRUE), 
                min=min(value, na.rm=TRUE), 
                median=median(value, na.rm=TRUE), 
                std=sd(value, na.rm=TRUE), 
                obs=n())
    
    return(desc_stats)
}
```


```{r}
# Prepare for loop
# Load shapefile
shape <- read_sf(paste0(dir_shp, 'MENA_ADM2.shp')) %>%                            #Change filename  
  st_transform(CRS_WGS) %>%
  st_make_valid() %>%
  # The Number of districts
  mutate(ID = seq.int(1, n()))

shape_df <- shape %>%
  st_drop_geometry()

#PREPARE LOOP OVER MONTHS
months <- c(paste0('0', c(1:9)), 10:12)
years <- seq(2001, 2020, 1)

#Create data frame
df_stat <- data.frame()

#Extract precipitation values
for (YEAR in years) {
  
  for(MONTH in months) {
    
    raster <- raster(paste0(dir_precip, '3B-MO.MS.MRG.3IMERG.', YEAR, MONTH, '01-S000000-E235959.', MONTH, '.V06B.HDF5.nc4'))
    
    clipped <- terra::crop(raster, shape)
    
    # stats at national level
    df_temp <- desc_stats_fun(clipped, shape) %>%
      mutate(years = YEAR,
             months = MONTH)

    df_stat <- bind_rows(df_stat, df_temp)
    }
  }

df_stat <- df_stat %>%
  left_join(shape_df, by = 'ID') %>%
  dplyr::select(ID_ADM, ID, mean, max, min, median, std, obs, years, months)

month_levels <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

#Create col by month name
df_stat <- df_stat %>%
  mutate(months = as.numeric(months),
         month = month.abb[months],
         month = factor(month, levels = month_levels))

write_csv(df_stat, paste0(dir_index, 'df_stat.csv'))
```

```{r}
df_stat <- read_csv(paste0(dir_out, 'df_stat.csv'))

#Transform temperature to measure per months mm/month for an easier interpretation

prec_month <- function(x) {
  x*720
}

vars <- names(df_stat)[3:7]
vars <- setNames(vars, paste0(vars, "_month")) # create new column names
df_stat <- df_stat %>% mutate_each_(funs(prec_month), vars)

YEAR_LIST <- c(2000, 2005, 2010, 2015, 2020)
df_full <- shape_df %>%
  dplyr::select(c(ID_ADM))

for (i in 1:(length(YEAR_LIST) - 1)) {
  
  YEAR_BEGIN <- YEAR_LIST[i] + 1
  YEAR_END <- YEAR_LIST[i+1]
  
  df1 <- df_stat %>%
    filter(years >= YEAR_BEGIN & years <= YEAR_END) %>%
    group_by(ID_ADM, month)%>%
    summarise(value = mean(mean_month)) %>%
    ungroup() %>%
    group_by(ID_ADM) %>%
    mutate(lag = lag(value),
           abs_value = abs(lag - value) %>% as.numeric()) %>%
    ungroup() %>%
    group_by(ID_ADM)%>%
    mutate(mean_val = mean(abs_value, na.rm = TRUE))

  diff_prec <- df1 %>%
    group_by(ID_ADM)%>%
    summarise(average_diff_prec = mean(abs_value, na.rm = TRUE))

  colnames(diff_prec)[2] <- paste0('PRECIP_DIFF_', YEAR_BEGIN, '_', YEAR_END)
  
  df_full <- left_join(df_full, diff_prec, by = 'ID_ADM')
}

write_csv(df_full, file = paste0(dir_index, "Pecipitation_ADM2.csv"))
```